### ISSUE TITLE
What would cause the `_hostIDQueue` to not get executed when attempting a postMessage?

### ISSUE THREAD

**Issue by NullVoxPopuli** [dumbmatter/promise-worker-bi#2]
not sure what I did, but using latest here, 
![image](https://user-images.githubusercontent.com/199018/70876739-c3403600-1f88-11ea-9899-b56d83b7e518.png)

but nothing is flushing the _hostIDQueue, so the "actuallyPostMessage" function from above the screenshot is never executed :-\

**Comment by NullVoxPopuli** [comment]
looks like adding this gets the alternate code path to fire in that promise:
```ts
    let worker = new Worker(path);
    let promiseWorker = new PWBHost(worker);
    promiseWorker._hostIDQueue = undefined;
```
it says that it's not going to send until hostID is known... but I wonder if that comment is out of date?

**Comment by NullVoxPopuli** [comment]
ok, so... disabling the hostIDQueue revealed that the worker creation never succeeded, because of a syntax error.
do we need tho hostIDQueue? It seemed to work without it? idk

**Comment by dumbmatter** [comment]
It's not needed if you're using a web worker. But it can be useful if you use a shared worker.

`hostID` is a unique identifier that the shared worker assigns to each window, so it can keep track of them (send messages to individual windows, and close connections when a window closes... the shared worker spec does not help you much with that stuff!). That means there is some delay in `hostID` being assigned, since communication between the window and worker is async. Without `hostIDQueue`, there would be a race condition where the window could send messages to the worker before `hostID` was known.

This matters if you are relying on the `hostID` value that comes along with messages to your shared worker. Like imagine you send a message from a window to the worker, and then deep in some subsequent code (maybe it's async, maybe it's event based, whatever) you want to send a message back to that specific window. You need to know the `hostID` to identify that window.

Writing all that up, it does seem pretty complicated. Maybe there is a better way of doing it. But it works for my purposes :) and before I added `hostIDQueue` I did actually see that race condition happen in production!

Also if you think there's anything I could do to improve error handling in your situation, let me know. I know handling errors in workers can be a pain.
